// Shared inline styles for the feature explorer (lifted out of App.jsx).

export const styles = {
  container: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: '16px',
    gap: '4px',
    overflow: 'hidden',
    background: 'var(--bg)',
    color: 'var(--text)',
  },
  header: {
    flexShrink: 0,
  },
  title: {
    fontSize: '22px',
    fontWeight: '600',
    marginBottom: '2px',
    color: 'var(--text-heading)',
  },
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '13px',
    margin: 0,
  },
  mainContent: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: '3fr 2fr',
    gap: '16px',
    minHeight: 0,
    overflow: 'hidden',
  },
  leftPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  embeddingPanel: {
    flex: 1,
    background: 'var(--bg-card)',
    borderRadius: '8px',
    border: '1px solid var(--border)',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '300px',
    minWidth: 0,
    overflow: 'hidden',
  },
  embeddingContainer: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  histogramRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '12px',
    flexShrink: 0,
    height: '100px',
    marginBottom: '4px',
  },
  histogramPanel: {
    background: 'var(--bg-card)',
    borderRadius: '8px',
    border: '1px solid var(--border)',
    padding: '8px',
    overflow: 'hidden',
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
    flexShrink: 0,
  },
  panelTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--text-heading)',
  },
  rightPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    minHeight: 0,
    minWidth: 0,
    height: '100%',
    overflow: 'hidden',
  },
  searchBar: {
    display: 'flex',
    gap: '8px',
    flexShrink: 0,
  },
  searchInput: {
    flex: 0.81,
    padding: '8px 12px',
    fontSize: '13px',
    border: '1px solid var(--border-input)',
    borderRadius: '6px',
    outline: 'none',
    background: 'var(--bg-input)',
    color: 'var(--text)',
  },
  sortSelect: {
    padding: '8px 12px',
    fontSize: '13px',
    border: '1px solid var(--border-input)',
    borderRadius: '6px',
    background: 'var(--bg-input)',
    color: 'var(--text)',
    cursor: 'pointer',
  },
  stats: {
    padding: '4px 0',
    fontSize: '12px',
    color: 'var(--text-secondary)',
    flexShrink: 0,
  },
  featureList: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingRight: '8px',
    minHeight: 0,
  },
  loading: {
    textAlign: 'center',
    padding: '40px',
    color: 'var(--text-secondary)',
  },
  error: {
    textAlign: 'center',
    padding: '40px',
    color: '#c00',
  },
  colorSelect: {
    padding: '4px 8px',
    fontSize: '12px',
    border: '1px solid var(--border-input)',
    borderRadius: '4px',
    background: 'var(--bg-input)',
    color: 'var(--text)',
    cursor: 'pointer',
  },
  clearButton: {
    padding: '4px 12px',
    fontSize: '12px',
    border: '2px solid var(--accent)',
    borderRadius: '4px',
    background: 'transparent',
    color: 'var(--accent)',
    fontWeight: '600',
    cursor: 'pointer',
  },
}
